### PR TITLE
368 resize no decorations macos subclass

### PR DESCRIPTION
**Pull request by sodiumjoe**
depends on https://github.com/tomaka/winit/pull/408 to work properly

### CODE REVIEW

**Comment by sodiumjoe** [comment]
So, I'm actually working on a different way to hide the titlebar:

```rust
                if pl_attrs.titlebar_hidden {
                    window.setTitleVisibility_(appkit::NSWindowTitleVisibility::NSWindowTitleHidden);
                    window.setTitlebarAppearsTransparent_(YES);
                    let button = window.standardWindowButton_(NSWindowButton::NSWindowFullScreenButton);
                    msg_send![button, setHidden:YES];
                    let button = window.standardWindowButton_(NSWindowButton::NSWindowMiniaturizeButton);
                    msg_send![button, setHidden:YES];
                    let button = window.standardWindowButton_(NSWindowButton::NSWindowCloseButton);
                    msg_send![button, setHidden:YES];
                    let button = window.standardWindowButton_(NSWindowButton::NSWindowZoomButton);
                    msg_send![button, setHidden:YES];
```

This is basically just `.fullsize_content_view(true)` and also hiding the buttons themselves. I think this is better than using `borderlessWindowMask` because it leaves the rounded corners, and keeps the shadow behavior for active windows.

The only thing I still would like to figure out is the weird behavior in external monitors I noted in https://github.com/jwilm/alacritty/pull/947#issuecomment-360908642.

Once (if) I figure that out, I think I may change this PR to just add another attribute `.titlebar_buttons_hidden`.

**Comment by sodiumjoe** [comment]
@robertgzr Hey, was wondering if you had a chance to look at this. I think I'll just open my own PR to winit if you don't have time to look at this. Thanks!

**Comment by robertgzr** [comment]
@sodiumjoe sorry about the radio silence

Did you figure out something for the external monitor issue?
> The only thing I still would like to figure out is the weird behavior in external monitors I noted in jwilm/alacritty#947 (comment).

I actually think it's a good idea to let people from upstream look at this because I don't really know much about the cocoa parts we touch here...

**Comment by sodiumjoe** [comment]
@robertgzr sorry, I got impatient. 

I haven't had a chance to figure out the dpi thing, because I mostly work on this at home, and my external monitor setup is at work. I'll try to dig into it this week. 

the hidden titlebar buttons is more or less orthogonal to that though, so imo, we should try to get all these extensions merged regardless. if you're still trying to get this pr merged, I'd like to add one more commit and I'll close my other PR.

**Comment by robertgzr** [comment]
Once https://github.com/tomaka/winit/pull/408 get's merged I would be happy to merge this and update https://github.com/tomaka/winit/pull/389 :)

**Comment by sodiumjoe** [comment]
ok sounds good, thanks!

**Pull request closed without merging**
